apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: fwk6rduhp-go 
  janus-idp.io/tekton: fwk6rduhp-go
  backstage.io/kubernetes-id: fwk6rduhp-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fwk6rduhp-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  